env:
  global:
    - CC_TEST_REPORTER_ID=cdc75eaf44ab340391ebe7bae0e986bc418615b4d34d90eef6fffbf1166571b4
language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - composer self-update
  - composer install --dev
script:
  - vendor/bin/robo test:coverage-codeclimate
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
  